#启动端口
server:
  port: 8080
#相关配置
spring:
  #  security:
  #    user:
  #      name: 1526706882@qq.com   # 用户名
  #      password: 123456  # 密码
  #      roles: # 角色
  #        - user
  #        - admin

  datasource:
    url: jdbc:mysql://localhost:3306/backend?Unicode=true&characterEncoding=UTF-8
    username: root
    password: '030701'
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: kina_zhang423@163.com
    password: HDEUNICDUMBKZYQH
    port: 465
    properties:
      from: kina_zhang423@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

  servlet:
    #      http:
    #        enabled: true                # 启用http上传
    #        max-request-size: 1GB         # 上传文件总的最大值 默认10MB
    #        max-file-size: 100MB         #单个文件最大值 默认10MB
    #        #        file-size-threshold: 512KB   # 当上传文件达到指定配置量的时候会将文件内容写入磁盘
    #        location: /home/kiakiana_423/UploadTest             # 设置上传的临时目录
    multipart:
      enabled: true                 # 启用http上传
      max-file-size: 100MB          #单个文件最大值 默认10MB
      max-request-size: 1GB         # 上传文件总的最大值 默认10MB
      file-size-threshold: 1MB      # 当上传文件达到指定配置量的时候会将文件内容写入磁盘
      location: /home/kiakiana_423/UploadTest/             # 设置上传的临时目录
#
#        file:
#          #上传路径
#          path: /home/kiakiana_423/UploadTest
#        access:
#          base-url:
#            #访问路径
#            file: /home/kiakiana_423/UploadTest

